export const GBF_GLOBAL_GOALS           = 'GBF-GOALS';
export const GBF_GLOBAL_TARGETS         = 'GBF-TARGETS';
export const GBF_GLOBAL_GOALS_TARGETS   = 'GBF-GOALS-TARGETS';
export const GBF_TARGETS_CONSIDERATIONS = 'GBF-TARGETS-CONSIDERATIONS'
